apps/stack/urls.py
from django.urls import path

from apps.stack.views import *
app_name = 'stack'

urlpatterns = [
    path("",dashboard,name="index"),
    path("signup",get_signup,name="signup"),
    path("signin",get_signin,name="signin"),
    path("logout",get_logout,name="logout"),

    path("addquestion",get_question,name="addquestion"),
    path("addanswer/<int:pk>",get_answer,name="addanswer"),
    path("reply/<int:pk>",get_reply,name="reply")

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.stack.urls'))
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

apps/stack/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User


class User(AbstractUser):

    username = models.CharField(max_length=50, unique=True)
    fullname = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, unique=True)
    address = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    image = models.FileField(upload_to='uploads/%Y/%m/%d', null=True)
    create_at = models.DateTimeField(auto_now_add=True, null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Question(BaseModel):
    name = models.CharField(max_length=255)
    description=models.TextField(null=True)
    tag = models.CharField(max_length=100)
    upvote = models.IntegerField(blank=True, null=True)
    downvote = models.IntegerField(blank=True, null=True)

    def __str__(self) -> str:
        return self.created_by.username + "/ " + self.name[0:20]


class Answer(BaseModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.TextField()
    upvote = models.IntegerField(null=True, blank=True)
    downvote = models.IntegerField(null=True, blank=True)

    def __str__(self) -> str:
        return self.question.name[0:20] + "/" + self.name[0:20]


class Reply(BaseModel):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    name = models.TextField()

    def __str__(self) -> str:
        return self.answer.name[0:20] + "/" + self.name[0:20]

apps/stack/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *
from django import forms


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields=["username","fullname","email","phone","address","image"]

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields=["name","description","tag"]

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields=["name",]

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields=["name",]        

apps/stack/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from .forms import *
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout


from django.contrib.auth.decorators import login_required


def get_signup(request):
    if request.method == "POST":
        form = UserForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Signup successfully")
            return redirect("stack:signin")

    else:
        form = UserForm()
    context = {'form': form}

    return render(request, "pages/signup.html", context)


def get_signin(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Signin successfully")

                return redirect("/")
    else:
        form = AuthenticationForm()
    context={
        'form':form
    }    
    return render(request, "pages/signin.html",context)

def get_logout(request):
    logout(request)
    messages.success(request, "Logout successfully")
    return redirect("stack:signin")
    
@login_required(login_url="stack:signin")
def dashboard(request):
    enquires=Question.objects.order_by("-created_at")
    context={
        'enquires':enquires,
    }
    return render(request, "pages/index.html",context)

def get_question(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.created_by = request.user
            data.save()
            messages.success(request, "Question Added successfully")
            return redirect("/")
    else:
        form=QuestionForm()
    context={
        "form":form
    }         
    return render(request,"pages/question.html",context) 


def get_answer(request,pk):
    questions=Question.objects.get(id=pk)

    if request.method=="POST":
        form=AnswerForm(request.POST)
        form.is_valid()
        data=form.save(commit=False)
        data.created_by=request.user
        data.question=questions

        form.save()
        messages.success(request, "Answer Added successfully")
        return redirect('/')
    else:
        form=AnswerForm()
    context={
        "form":form,
        'questions':questions,

    }  
    return render(request,"pages/answer.html",context)

def get_reply(request,pk):
    answers=Answer.objects.get(id=pk)
    if request.method=="POST":
        form=ReplyForm(request.POST)
        form.is_valid()
        data=form.save(commit=False)
        data.created_by=request.user
        form.save()
        messages.success(request, "Reply Added successfully")
        return redirect('/')
    else:
        form=AnswerForm()
    context={
        "form":form,
        'answers':answers
    }  
    return render(request,"pages/reply.html",context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'styles.css' %}" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <title>Bill management</title>
</head>

<body>
 


  {% include 'includes/header.html' %}



  {% block body_content %}{% endblock %}
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show message"  id="myElem" style="width: 25%; margin-left:70% ;" role="alert">
      {{ message }}
      </button>
  </div>
  {% endfor %}
  {% endif %}

<script>
  $("#myElem").show().delay(5000).queue(function(n) {
  $(this).hide(); n();
});
</script>

</body>

</html>

templates/includes/header.html
{% load static %}
<div class="header1">
    <nav>
        <a href="/"><img src="{%static 'image/logo .png' %}" class="logo"></a>
        <ul class="nav-linkss">

            <li><a href="/">About</a></li>
            <li><a href=""></a></li>


            {% if user.is_authenticated %}
            <a href="" class="btn1">Logout</a>


            {% else %}
            <a href="" class="btn1">Log In</a>

            {% endif %}

        </ul>

    </nav>
</div>

templates/pages/answer.html
{% extends "base.html"%}

{% load static %}

{% block body_content %}
{% load crispy_forms_tags %}
<br>
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Signin</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    
                    <div class="login-wrap p-4 p-lg-5">
                  
                        <form action="" class="signin-form" method="post" enctype="multipart/form-data">
                            
                            {% csrf_token %}
                            {{ form|crispy }}
               <br>
                <div class="form-group">
                    <button type="submit" class="form-control btn1  submit px-1">Add Question</button>
                </div>
                
              </form>
              <br>

            </div>
          </div>
            </div>
        </div>
    </div>
</section>

    {% endblock %}

templates/pages/index.html
{% extends "base.html"%}

{% load static %}

{% block body_content %}




{% for enquiry in enquires %}
<style>
	.profile-pic{
		max-width: 60px;
		max-height:70px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>
<div class="card " style="background-color: #F2F2F2; margin-top: 2%;margin-right: 7% ;margin-left: 7%;">
    <div class="card-header">
      <a href="{% url 'stack:addanswer' enquiry.id %}" style="text-decoration: none;  color:#6777ef ;;">{{enquiry.name}}</a>
      
    </div>
    <div class="card-body ">
      <blockquote class="blockquote mb-0">
        <p>{{enquiry.description}}</p>
        <footer class="blockquote-footer">{{enquiry.created_by}} <cite title="Source Title">{{enquiry.created_at|timesince}}</cite></footer>
        <img class="profile-pic" src="{{enquiry.created_by.image.url}}" >
      </blockquote>
    </div>
  </div>
{% endfor %}



{% endblock %}

templates/pages/question.html
{% extends "base.html"%}

{% load static %}

{% block body_content %}
{% load crispy_forms_tags %}
<br>
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Signin</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    
                    <div class="login-wrap p-4 p-lg-5">
                  
                        <form action="" class="signin-form" method="post" enctype="multipart/form-data">
                            
                            {% csrf_token %}
                            {{ form|crispy }}
               <br>
                <div class="form-group">
                    <button type="submit" class="form-control btn1  submit px-1">Add Question</button>
                </div>
                
              </form>
              <br>

            </div>
          </div>
            </div>
        </div>
    </div>
</section>

    {% endblock %}

templates/pages/questiondetails.html
{{questions.name}}

{% for comment in questions.answer_set.all %}
{{comment.name}}
{% endfor %}

templates/pages/reply.html
{% extends "base.html"%}

{% load static %}

{% block body_content %}
{% load crispy_forms_tags %}
<br>
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Reply</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    
                    <div class="login-wrap p-4 p-lg-5">
                  
                        <form action="" class="signin-form" method="post" enctype="multipart/form-data">
                            
                            {% csrf_token %}
                            {{ form|crispy }}
               <br>
                <div class="form-group">
                    <button type="submit" class="form-control btn1  submit px-1">Reply</button>
                </div>
                
              </form>
              <br>
            
            </div>
          </div>
            </div>
        </div>
    </div>
</section>

    {% endblock %}

templates/pages/signin.html
{% extends "base.html"%}

{% load static %}

{% block body_content %}
{% load crispy_forms_tags %}
<br>
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Signin</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    
                    <div class="login-wrap p-4 p-lg-5">
                  
                        <form action="" class="signin-form" method="post" enctype="multipart/form-data">
                            
                            {% csrf_token %}
                            {{ form|crispy }}
               <br>
                <div class="form-group">
                    <button type="submit" class="form-control btn1  submit px-1">Signin</button>
                </div>
                
              </form>
              <br>
              <small style="margin-left: 30%;"><a href="{% url 'stack:signup' %}">Not a member? Signup here</a></small>
            </div>
          </div>
            </div>
        </div>
    </div>
</section>

    {% endblock %}

templates/pages/signup.html
{% extends "base.html"%}

{% load static %}

{% block body_content %}
{% load crispy_forms_tags %}
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                <h2 class="heading-section">Signin</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    
                    <div class="login-wrap p-4 p-lg-5">
                  
                        <form action="" class="signin-form" method="post" enctype="multipart/form-data">
                            
                            <div class="form-group mb-3 label" >
                            
                                {% csrf_token %}
                                <div class="form-group mb-3">
                                    {{  form.username.label }}<br>{{  form.username }}
                                </div>
                                <div class="form-group mb-3">
                                    {{  form.fullname.label }}<br>{{  form.fullname }}
                                </div>
                                <div class="form-group mb-3">
                                    {{  form.email.label }}<br>{{  form.email }}
                                </div>
                                <div class="form-group mb-3">
                                    {{  form.phone.label }}<br>{{  form.phone }}
                                </div>
                                <div class="form-group mb-3">
                                    {{  form.address.label }}<br>{{  form.address }}
                                </div>
                                <div class="form-group mb-3">
                                    {{  form.image.label }}<br>{{  form.image }}
                                </div>
                                <div class="form-group mb-3">
                                    {{  form.password1.label }}<br>{{ form.password1 }}
                                </div>
                                <div class="form-group mb-3">
                                    {{  form.password2.label }}<br>{{ form.password2 }}
                                </div>
                               
                           
                            </div>
               <br>
                <div class="form-group">
                    <button type="submit" class="form-control btn1  submit px-1">Signin</button>
                </div>
                
              </form>
              <div class="form-group mb-3">
								
                {{form.errors}}
            </div>
            
            
            </div>
          </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}